package dev.misei.domain.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Billing implements Comparable<Billing> {
    //FEATURE: We could do some insight about price or who sold the most

    //Autogenerated
    @Id
    private String id;

    private Warehouse warehouseCopyWhere;
    private Material materialCopyWhat;
    private User userCopyWho;
    private long timestampWhen;

    @Override
    public int compareTo(Billing billing) {
        return Long.compare(timestampWhen, billing.timestampWhen);
    }
}
