package dev.misei.domain.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DocumentReference;

import java.util.HashSet;
import java.util.Set;

@Document
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Stand {

    //FEATURE QR CODE or autogenerated if you dont care about which stand or generic
    @Id
    private String id;

    @DocumentReference
    private Set<Material> materials = new HashSet<>();

    /* Feature
    private String section;
    private String level;
    private ... Size;*/
    /* FEATURE A stand has a door and cannot be opened freely*/

    private Stand addMaterial(Material material) {
        materials.add(material);
        return this;
    }
}
