package dev.misei.domain.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.HashSet;
import java.util.Set;


@Data
@AllArgsConstructor
@NoArgsConstructor
public class Stand {

    //FEATURE QR CODE or autogenerated if you dont care about which stand or generic
    private String id;

    private Set<Material> materials = new HashSet<>();

    /* Feature
    private String section;
    private String level;
    private ... Size;*/
    /* FEATURE A stand has a door and cannot be opened freely*/

    public Stand addMaterial(Material material) {
        materials.add(material);
        return this;
    }

    @Override
    public boolean equals(Object o) {
        return (o instanceof Stand that) && this.id.equalsIgnoreCase(that.id);
    }
}
